#
# COPYRIGHT Ericsson 2020
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-eo-api-gateway.name" . }}-psp-binding
  labels:
    app: {{ template "eric-eo-api-gateway.name" . }}
    chart: {{ template "eric-eo-api-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- include "eric-eo-api-gateway.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-eo-api-gateway.helm-annotations" .| nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "eric-eo-api-gateway.release.name" . }}-allowed-use-privileged-policy
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-eo-api-gateway.name" . }}-sa