global:
  hosts:
    wano: wano.ericsson.example.com
    so: so.ericsson.example.com
    sdd: sdd.ericsson.example.com
    vnfm: vnfm.ericsson.example.com
    iam: iam.ericsson.example.com
    pf: pf.ericsson.example.com
    uds: uds.ericsson.example.com
    gr: gr.ericsson.example.com
  registry:
    url: armdocker.rnd.ericsson.se
  iam:
    clientId: eo
    adminSecret: eric-sec-access-mgmt-creds
    userKey: kcadminid
    passwordKey: kcpasswd
    cacert:
      secretName: iam-cacert-secret
      key: tls.crt
      filePath: iam/ca.crt
  timezone: UTC

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

imageCredentials:
  # repoPath include the image path relative to the registry url, excluding image name
  repoPath: proj-orchestration-so
  pullPolicy: IfNotPresent
  registry:
    url:
  # overrides global registry
  #url: armdocker.companyA.se
  # Secret must be manually created in the namespace, no default value
  #pullSecret: eric-adp-example-secret

images:
  eric-eo-api-gateway:
    name: eric-eo-api-gateway
    repository: IMAGE_REPO
    tag: IMAGE_TAG
  init:
    name: so-base
    tag: 1.0.0-9
  keycloakClient:
    name: keycloak-client
    tag: 1.0.0-17

#######################################################################
iam:
  issuerPath: /auth/realms/master
  createIamClient: true
  kubernetesSecret: iam-client-secret
  secretKey: clientSecret
  token:
    context: /oauth2/auth/realms/*/protocol/openid-connect/token
#######################################################################

so:
  dashboard:
    context: /dashboard/**
    service: http://eric-eo-dashboard
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  engine:
    context: /orchestration/**
    service: http://eric-eo-engine
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  onboarding:
    context: /onboarding/**
    service: http://eric-eo-onboarding
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  topology:
    context: /topology/**
    service: http://eric-eo-topology
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  topologysynchronisation:
    context: /topology-synchronisation/**
    service: http://eric-eo-topology-synchronisation-service
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  orchestrationcockpit:
    context: /orchestrationcockpit/**
    service: http://eric-eo-orchestrationcockpit
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  catalogmanager:
    context: /catalog-manager/**
    service: http://eric-eo-catalog-manager
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  gui:
    context: /**
    service: http://eric-eo-orchestration-gui
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  subsystemsmanager:
    context: /subsystems-manager/**
    service: http://eric-eo-subsystems-manager
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  subsystemsmanagement:
    context: /subsystem-manager/**
    service: http://eric-eo-subsystem-management
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  ipmanager:
    depricatedcontext: /ip-manager/**
    context: /ipam/**
    service: http://eric-eo-ipaddress-manager
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  metric:
    context: /so/metrics/**
    service: http://eric-so-pm-server:9090
usermgmt:
  ui:
    context: /idm/usermgmt*ui/**
    service: http://eric-eo-usermgmt-ui
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  service:
    context: /idm/usermgmt/**,/idm/rolemgmt/**
    service: http://eric-eo-usermgmt
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
subsystemsmgmt:
  ui:
    context: /subsystemsmgmt*ui/**
    service: http://eric-eo-subsystemsmgmt-ui
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
ipam:
  ui:
    context: /ipam*ui/**
    service: http://eric-eo-ipam-ui
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
tenantmgmt:
  service:
    context: /idm/tenantmgmt/**
    service: http://eric-eo-tenantmgmt
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
logs:
  visualizer:
    context: /log/viewer/**
    service: http://eric-data-visualizer-kb
    branding:
      context: /logs/**
      removePath: 1
    routeOrder: -1
metric:
  context: /metrics/viewer/**
  service: http://eric-pm-server:9090
  routeOrder: -1
bro:
  context: /backup-restore/**
  service: http://eric-ctrl-bro:7001
  rateLimit:
    maxAccess: 500
    # resetTime in seconds
    resetTime: 1
gr:
  orchestrator:
    context: /**
    service: http://eric-eo-gr-orchestrator
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
nfvo:
  notifications:
    context: /v3/notfications/**
    service: http://notfications/v3/notfications
  subscriptions:
    context: /v3/subscriptions/**
    service: http://notfications/v3/subscriptions
  cmdbproxyservicedesign:
    context: /services/cmdb-services-ws/service-design/**
    service: http://cmdb-proxy/services/cmdb-services-ws/service-design
  cmdbproxyqueryservices:
    context: /services/cmdb-services-ws/query-services/**
    service: http://cmdb-proxy/services/cmdb-services-ws/query-services
  cmdbproxynotifications:
    context: /cmdbproxy-notifications/**
    service: http://cmdb-proxy/notificatons.*
wano:
  gui:
    context: /**
    service: http://eric-eo-wano-ui
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  nbi:
    context: /wano-nbi/**
    service: http://eric-eo-wano-nbi
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
sdd:
  context: /**
  service: http://sdd-sim:8222

uds:
  apx:
    context: /udsapx/policy/**
    service: http://eric-oss-uds-policy-ui:9090
    rateLimit:
      maxAccess: 500
      resetTime: 1

  artifact:
    context: /artifact/**
    service: http://eric-oss-uds-policy-artifact-ui:8095
    rateLimit:
      maxAccess: 500
      resetTime: 1
  
  context: /**
  service: http://eric-oss-uds-authenticator:8285 
 
vnfm:
  gui:
    context: /vnfm/**
    service: http://eric-am-common-wfs-ui
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  onboarding:
    context: /vnfm/onboarding/**
    service: http://eric-am-onboarding-service
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  wfs:
    context: /vnfm/wfs/api/lcm/v2/cluster
    service: http://eric-am-common-wfs
  nbi:
    context: /vnflcm/**
    service: http://eric-eo-evnfm-nbi
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1

vnflcm:
  gui:
    context: /**
    service: http://eric-vnflcm-ui:80
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1
  #sol002 the rest endpints should directly reach vnflcm-service container.
  vevnfmem:
    context: /vevnfmem/vnflcm/**
    service: http://eric-vnflcm-service:8080
    rateLimit:
      maxAccess: 500
      # resetTime in seconds
      resetTime: 1

policy:
  apex:
    context: /policy/apex-pdp/**
    service: https://eric-oss-pf-apex:6969
    rateLimit:
      maxAccess: 1000
      # resetTime in seconds
      resetTime: 1
  policyapi:
    context: /policy/api/**
    service: https://eric-oss-pf-policyapi:6969
    rateLimit:
      maxAccess: 1000
      # resetTime in seconds
      resetTime: 1
  policypap:
    context: /policy/pap/**
    service: https://eric-oss-pf-pap:6969
    rateLimit:
      maxAccess: 1000
      # resetTime in seconds
      resetTime: 1
  policyxacml:
    context: /policy/pdpx/**
    service: https://eric-oss-pf-xacml:6969
    rateLimit:
      maxAccess: 1000
      # resetTime in seconds
      resetTime: 1
  policydrools:
    context: /policy/drools/**
    service: https://eric-oss-pf-drools:6969
    rateLimit:
      maxAccess: 1000
      # resetTime in seconds
      resetTime: 1
  policydist:
    context: /policy/dist/**
    service: https://eric-oss-pf-policy-dist:6969
    rateLimit:
      maxAccess: 1000
      # resetTime in seconds
      resetTime: 1

dmaap:
  context: /dmaap-mr/**
  service: https://eric-oss-dmaap:3905
  rateLimit:
      maxAccess: 1000
      # resetTime in seconds
      resetTime: 1

ecm:
  service:
    context: /ecm_service/**
    path: https://ecm-services

cloud:
  mgr:
    gui:
      context: /cloudMgrGui/**
      path: https://cloud-mgr-gui

open:
  am:
    context: /openam/**
    service: https://openam

crypto:
  context: /generic/v1/**
  service: http://eric-eo-evnfm-crypto
  rateLimit:
    maxAccess: 500
    # resetTime in seconds
    resetTime: 1

jvm:
  heap:
    min: "300m"
    max: "1200m"

replicas: 1

resources:
  requests:
    memory: 1512Mi
    cpu: 100m
  limits:
    memory: 1512Mi
    cpu: 1000m

probe:
  readiness:
    initialDelaySeconds: 60 # 1 min
    periodSeconds: 5 # 5 sec
    timeoutSeconds: 2 # 2 sec
  liveness:
    initialDelaySeconds: 600 # 10 min
    periodSeconds: 5 # 5 sec
    timeoutSeconds: 10 # 10 sec
    failureThreshold: 3
logging:
  format:
    json: true

prometheus:
  path: /actuator/prometheus
  port:  8080
  scrape: true
session:
  timeout: 3600
